# Generated by Django 4.2.2 on 2023-06-26 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('image', models.ImageField(null=True, upload_to='services/icons/', verbose_name='Serice Icon')),
                ('description', models.TextField(verbose_name='Description')),
                ('order_by', models.IntegerField(unique=True, verbose_name='Order By')),
            ],
        ),
    ]
