# Generated by Django 4.2.2 on 2023-06-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='code',
            field=models.CharField(default='dummy', max_length=5, verbose_name='service code'),
            preserve_default=False,
        ),
    ]
