# Generated by Django 4.2.2 on 2023-06-26 12:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_editorjs_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mysite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='service_requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_description', models.TextField(verbose_name='Service Description')),
                ('created', models.DateField(verbose_name='Date Created')),
                ('phone_number', models.IntegerField(verbose_name='Phone Number')),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.service')),
            ],
        ),
        migrations.CreateModel(
            name='jobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('type', models.CharField(max_length=20, verbose_name='Type')),
                ('role', models.CharField(max_length=20, verbose_name='Role')),
                ('experience_min', models.IntegerField()),
                ('experience_max', models.IntegerField()),
                ('premium', models.BooleanField(default=False)),
                ('description', django_editorjs_fields.fields.EditorJsJSONField()),
                ('category', models.TextField()),
                ('salary_lower_range', models.TextField()),
                ('salary_upper_range', models.TextField()),
                ('created', models.DateField(auto_now_add=True, verbose_name='Date Posted')),
                ('modified', models.DateField(verbose_name='Date Modified')),
                ('postedby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
